# Codecov configuration
# https://docs.codecov.com/docs/codecov-yaml

codecov:
  require_ci_to_pass: true
  notify:
    wait_for_ci: true

coverage:
  precision: 2
  round: down
  range: "50...90"

  status:
    project:
      default:
        target: 60%
        threshold: 2%
        informational: false
        only_pulls: false

      # Separate targets for Rust and Python
      rust:
        target: 65%
        threshold: 2%
        flags:
          - rust
        paths:
          - crates/

      python:
        target: 70%
        threshold: 2%
        flags:
          - python
        paths:
          - python/fast_yaml/

    patch:
      default:
        target: 70%
        threshold: 5%
        informational: false

# Flag configuration
flag_management:
  default_rules:
    carryforward: true
    statuses:
      - type: project
        target: auto
        threshold: 2%
      - type: patch
        target: 70%

  individual_flags:
    - name: rust
      paths:
        - crates/
      carryforward: true
      after_n_builds: 1

    - name: python
      paths:
        - python/fast_yaml/
      carryforward: true
      after_n_builds: 1

# Component configuration for granular coverage tracking
component_management:
  default_rules:
    statuses:
      - type: project
        target: 60%
        threshold: 2%

  individual_components:
    - component_id: core
      name: "Core Parser"
      paths:
        - crates/fast-yaml-core/**

    - component_id: linter
      name: "Linter Engine"
      paths:
        - crates/fast-yaml-linter/**

    - component_id: parallel
      name: "Parallel Processing"
      paths:
        - crates/fast-yaml-parallel/**

    - component_id: ffi
      name: "FFI Utilities"
      paths:
        - crates/fast-yaml-ffi/**

    - component_id: python
      name: "Python Bindings"
      paths:
        - python/fast_yaml/**
        - python/src/**

# Ignore test files and generated code
ignore:
  - "tests/**"
  - "benches/**"
  - "examples/**"
  - "python/tests/**"
  - "**/*_test.rs"
  - "**/test_*.py"
  - "**/*.pyi"
  - "target/**"

# PR comment configuration
comment:
  layout: "header,diff,flags,components,files"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true
  hide_project_coverage: false

# Parsers configuration
parsers:
  gcov:
    branch_detection:
      conditional: true
      loop: true
      macro: false
      method: false
