"""Generate python/tests/data/yaml_test_suite_xfail.txt by running pytest and collecting failures."""

import os
import subprocess
import sys
import tempfile
import xml.etree.ElementTree as ET
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TEST = ROOT / "tests" / "test_yaml_test_suite.py"
OUT = ROOT / "tests" / "data" / "yaml_test_suite_xfail.txt"
TAG = "data-2022-01-17"


def main():
    if not os.environ.get("YAML_TEST_SUITE_PATH"):
        print("error: YAML_TEST_SUITE_PATH not set", file=sys.stderr)
        return 2

    try:
        import fast_yaml  # noqa: F401
    except ImportError:
        print(
            "error: fast_yaml not importable; run `uv run maturin develop` first",
            file=sys.stderr,
        )
        return 2

    with tempfile.NamedTemporaryFile(suffix=".xml", delete=False) as tmp:
        junit = tmp.name

    env = {**os.environ, "YAML_TEST_SUITE_XFAIL_COLLECT": "1"}
    subprocess.run(
        [
            "uv", "run", "pytest",
            str(TEST),
            "-q",
            "--tb=no",
            "-p", "no:cacheprovider",
            f"--junitxml={junit}",
        ],
        env=env,
        cwd=ROOT,
        check=False,
    )

    tree = ET.parse(junit)
    failing = sorted({
        tc.get("name").split("[", 1)[1].rstrip("]")
        for tc in tree.iter("testcase")
        if any(tc.find(t) is not None for t in ("failure", "error"))
    })

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(
        f"# Known-failing cases from yaml-test-suite (tag: {TAG}).\n"
        "# Generated by python/scripts/gen_yaml_test_suite_xfail.py\n"
        "#\n"
        "# Syntax:\n"
        "#   <case-id>       — strict xfail (if case starts passing, CI turns red; remove it)\n"
        "#   <case-id> ?     — non-strict xfail (allowed to pass on some platforms)\n"
        "#   # comment       — ignored\n"
        "#\n"
        "# Keep the list sorted. One id per line.\n"
        "# Append a trailing `# #<issue>` comment to link a GitHub issue.\n"
        "#\n"
        "# To regenerate after suite or parser changes:\n"
        "#   YAML_TEST_SUITE_PATH=/path/to/yaml-test-suite \\\n"
        "#     uv run python scripts/gen_yaml_test_suite_xfail.py\n"
        + ("\n".join(failing) + "\n" if failing else ""),
        encoding="utf-8",
    )
    print(f"wrote {len(failing)} ids -> {OUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
