/* auto-generated by NAPI-RS */
/* eslint-disable */
/** Options for YAML serialization. */
export interface DumpOptions {
  /** If true, sort object keys alphabetically (default: false) */
  sortKeys?: boolean;
  /**
   * Allow unicode characters (default: true).
   * Note: yaml-rust2 always outputs unicode; this is accepted for API compatibility.
   */
  allowUnicode?: boolean;
}

/**
 * Serialize a JavaScript object to a YAML string.
 *
 * This is equivalent to js-yaml's `safeDump()` and `PyYAML`'s `safe_dump()`.
 *
 * # Arguments
 *
 * * `data` - A JavaScript object to serialize (Object, Array, string, number, boolean, null)
 * * `options` - Optional serialization options
 *
 * # Returns
 *
 * A YAML string representation of the object
 *
 * # Errors
 *
 * Throws an error if the object contains non-serializable types.
 *
 * # Example
 *
 * ```javascript
 * const { safeDump } = require('@fast-yaml/core');
 *
 * const yaml = safeDump({ name: 'test', value: 123 });
 * console.log(yaml); // 'name: test
value: 123
'
 * ```
 */
export declare function safeDump(
  data: unknown,
  options?: DumpOptions | undefined | null
): NapiResult<string>;

/**
 * Serialize multiple JavaScript objects to a YAML string with document separators.
 *
 * This is equivalent to js-yaml's `safeDumpAll()` and `PyYAML`'s `safe_dump_all()`.
 *
 * # Arguments
 *
 * * `documents` - An array of JavaScript objects to serialize
 * * `options` - Optional serialization options
 *
 * # Returns
 *
 * A YAML string with multiple documents separated by "---"
 *
 * # Errors
 *
 * Throws an error if:
 * - Any object cannot be serialized
 * - Total output size exceeds 100MB limit
 *
 * # Security
 *
 * Maximum output size is limited to 100MB to prevent memory exhaustion.
 *
 * # Example
 *
 * ```javascript
 * const { safeDumpAll } = require('@fast-yaml/core');
 *
 * const yaml = safeDumpAll([{ a: 1 }, { b: 2 }]);
 * console.log(yaml); // '---
a: 1
---
b: 2
'
 * ```
 */
export declare function safeDumpAll(
  documents: Array<unknown>,
  options?: DumpOptions | undefined | null
): NapiResult<string>;

/**
 * Parse a YAML string and return a JavaScript object.
 *
 * This is equivalent to js-yaml's `safeLoad()` and `PyYAML`'s `safe_load()`.
 *
 * # Arguments
 *
 * * `yaml_str` - A YAML document as a string
 *
 * # Returns
 *
 * The parsed YAML document as JavaScript objects (Object, Array, string, number, boolean, null)
 *
 * # Errors
 *
 * Throws an error if:
 * - The YAML is invalid
 * - Input exceeds size limit (100MB)
 *
 * # Security
 *
 * Maximum input size is limited to 100MB to prevent denial-of-service attacks.
 *
 * # Example
 *
 * ```javascript
 * const { safeLoad } = require('@fast-yaml/core');
 *
 * const data = safeLoad('name: test
value: 123');
 * console.log(data); // { name: 'test', value: 123 }
 * ```
 */
export declare function safeLoad(yamlStr: string): NapiResult<unknown>;

/**
 * Parse a YAML string containing multiple documents.
 *
 * This is equivalent to js-yaml's `safeLoadAll()` and `PyYAML`'s `safe_load_all()`.
 *
 * # Arguments
 *
 * * `yaml_str` - A YAML string potentially containing multiple documents
 *
 * # Returns
 *
 * An array of parsed JavaScript objects
 *
 * # Errors
 *
 * Throws an error if:
 * - The YAML is invalid
 * - Input exceeds size limit (100MB)
 *
 * # Security
 *
 * Maximum input size is limited to 100MB to prevent denial-of-service attacks.
 *
 * # Example
 *
 * ```javascript
 * const { safeLoadAll } = require('@fast-yaml/core');
 *
 * const docs = safeLoadAll('---
foo: 1
---
bar: 2');
 * console.log(docs); // [{ foo: 1 }, { bar: 2 }]
 * ```
 */
export declare function safeLoadAll(yamlStr: string): NapiResult<Array<unknown>>;

/**
 * Get the library version.
 *
 * Returns the version string of the fast-yaml-nodejs crate.
 *
 * # Examples
 *
 * ```javascript
 * const { version } = require('@fast-yaml/core');
 * console.log(version()); // "0.1.0"
 * ```
 */
export declare function version(): string;

// Aliases for js-yaml compatibility
export declare const load: typeof safeLoad;
export declare const dump: typeof safeDump;
