/* auto-generated by NAPI-RS */
/* eslint-disable */

// ============================================================================
// Schema Types (js-yaml compatible)
// ============================================================================

/**
 * YAML schema types for parsing behavior (js-yaml compatible).
 *
 * All schemas currently behave as `SAFE_SCHEMA` (safe by default).
 * The schema parameter is accepted for API compatibility with js-yaml.
 */
export type Schema = 'SafeSchema' | 'JsonSchema' | 'CoreSchema' | 'FailsafeSchema';

/** Safe schema constant (js-yaml compatible). */
export declare const SAFE_SCHEMA: Schema;
/** JSON schema constant (js-yaml compatible). */
export declare const JSON_SCHEMA: Schema;
/** Core schema constant (js-yaml compatible). */
export declare const CORE_SCHEMA: Schema;
/** Failsafe schema constant (js-yaml compatible). */
export declare const FAILSAFE_SCHEMA: Schema;

// ============================================================================
// Mark Class (error location tracking)
// ============================================================================

/**
 * Represents a position in a YAML source file.
 *
 * Used to indicate where errors occur during parsing.
 *
 * @example
 * ```javascript
 * const { Mark } = require('@fast-yaml/core');
 *
 * const mark = new Mark('<input>', 5, 10);
 * console.log(mark.name);   // '<input>'
 * console.log(mark.line);   // 5
 * console.log(mark.column); // 10
 * console.log(mark.toString()); // '<input>:5:10'
 * ```
 */
export declare class Mark {
  /** The name of the source (e.g., filename or '<input>'). */
  readonly name: string;
  /** The line number (0-indexed). */
  readonly line: number;
  /** The column number (0-indexed). */
  readonly column: number;

  /**
   * Create a new Mark instance.
   *
   * @param name - The source name (e.g., filename)
   * @param line - The line number (0-indexed)
   * @param column - The column number (0-indexed)
   */
  constructor(name: string, line: number, column: number);

  /**
   * Get a string representation of the mark.
   *
   * @returns format: "name:line:column"
   */
  toString(): string;
}

// ============================================================================
// Load Options (js-yaml compatible)
// ============================================================================

/** Options for YAML parsing (js-yaml compatible). */
export interface LoadOptions {
  /**
   * YAML schema to use for parsing (default: `SafeSchema`).
   * Currently all schemas behave as `SafeSchema` (safe by default).
   */
  schema?: Schema;
  /** Filename or source name for error messages (default: `<input>`). */
  filename?: string;
  /**
   * Allow duplicate keys in mappings (default: true).
   * Note: fast-yaml always allows duplicates; this is for API compatibility.
   */
  allowDuplicateKeys?: boolean;
}

// ============================================================================
// Dump Options
// ============================================================================

/** Options for YAML serialization. */
export interface DumpOptions {
  /** If true, sort object keys alphabetically (default: false) */
  sortKeys?: boolean;
  /**
   * Allow unicode characters (default: true).
   * Note: yaml-rust2 always outputs unicode; this is accepted for API compatibility.
   */
  allowUnicode?: boolean;
}

/**
 * Serialize a JavaScript object to a YAML string.
 *
 * This is equivalent to js-yaml's `safeDump()` and `PyYAML`'s `safe_dump()`.
 *
 * # Arguments
 *
 * * `data` - A JavaScript object to serialize (Object, Array, string, number, boolean, null)
 * * `options` - Optional serialization options
 *
 * # Returns
 *
 * A YAML string representation of the object
 *
 * # Errors
 *
 * Throws an error if the object contains non-serializable types.
 *
 * # Example
 *
 * ```javascript
 * const { safeDump } = require('@fast-yaml/core');
 *
 * const yaml = safeDump({ name: 'test', value: 123 });
 * console.log(yaml); // 'name: test
value: 123
'
 * ```
 */
export declare function safeDump(
  data: unknown,
  options?: DumpOptions | undefined | null
): NapiResult<string>;

/**
 * Serialize multiple JavaScript objects to a YAML string with document separators.
 *
 * This is equivalent to js-yaml's `safeDumpAll()` and `PyYAML`'s `safe_dump_all()`.
 *
 * # Arguments
 *
 * * `documents` - An array of JavaScript objects to serialize
 * * `options` - Optional serialization options
 *
 * # Returns
 *
 * A YAML string with multiple documents separated by "---"
 *
 * # Errors
 *
 * Throws an error if:
 * - Any object cannot be serialized
 * - Total output size exceeds 100MB limit
 *
 * # Security
 *
 * Maximum output size is limited to 100MB to prevent memory exhaustion.
 *
 * # Example
 *
 * ```javascript
 * const { safeDumpAll } = require('@fast-yaml/core');
 *
 * const yaml = safeDumpAll([{ a: 1 }, { b: 2 }]);
 * console.log(yaml); // '---
a: 1
---
b: 2
'
 * ```
 */
export declare function safeDumpAll(
  documents: Array<unknown>,
  options?: DumpOptions | undefined | null
): NapiResult<string>;

/**
 * Parse a YAML string and return a JavaScript object.
 *
 * This is equivalent to js-yaml's `safeLoad()` and `PyYAML`'s `safe_load()`.
 *
 * # Arguments
 *
 * * `yaml_str` - A YAML document as a string
 *
 * # Returns
 *
 * The parsed YAML document as JavaScript objects (Object, Array, string, number, boolean, null)
 *
 * # Errors
 *
 * Throws an error if:
 * - The YAML is invalid
 * - Input exceeds size limit (100MB)
 *
 * # Security
 *
 * Maximum input size is limited to 100MB to prevent denial-of-service attacks.
 *
 * # Example
 *
 * ```javascript
 * const { safeLoad } = require('@fast-yaml/core');
 *
 * const data = safeLoad('name: test
value: 123');
 * console.log(data); // { name: 'test', value: 123 }
 * ```
 */
export declare function safeLoad(yamlStr: string): NapiResult<unknown>;

/**
 * Parse a YAML string containing multiple documents.
 *
 * This is equivalent to js-yaml's `safeLoadAll()` and `PyYAML`'s `safe_load_all()`.
 *
 * # Arguments
 *
 * * `yaml_str` - A YAML string potentially containing multiple documents
 *
 * # Returns
 *
 * An array of parsed JavaScript objects
 *
 * # Errors
 *
 * Throws an error if:
 * - The YAML is invalid
 * - Input exceeds size limit (100MB)
 *
 * # Security
 *
 * Maximum input size is limited to 100MB to prevent denial-of-service attacks.
 *
 * # Example
 *
 * ```javascript
 * const { safeLoadAll } = require('@fast-yaml/core');
 *
 * const docs = safeLoadAll('---
foo: 1
---
bar: 2');
 * console.log(docs); // [{ foo: 1 }, { bar: 2 }]
 * ```
 */
export declare function safeLoadAll(yamlStr: string): NapiResult<Array<unknown>>;

/**
 * Get the library version.
 *
 * Returns the version string of the fast-yaml-nodejs crate.
 *
 * # Examples
 *
 * ```javascript
 * const { version } = require('@fast-yaml/core');
 * console.log(version()); // "0.1.0"
 * ```
 */
export declare function version(): string;

// ============================================================================
// js-yaml compatible load/loadAll with options
// ============================================================================

/**
 * Parse a YAML string with options (js-yaml compatible).
 *
 * This is the js-yaml compatible `load()` function that accepts an options object.
 * Currently all schemas behave as `SafeSchema` (safe by default).
 *
 * @param yamlStr - A YAML document as a string
 * @param options - Optional parsing options (schema, filename, etc.)
 * @returns The parsed YAML document as JavaScript objects
 * @throws Error if the YAML is invalid or input exceeds 100MB
 *
 * @example
 * ```javascript
 * const { load, SAFE_SCHEMA } = require('@fast-yaml/core');
 *
 * const data = load('name: test', { schema: 'SafeSchema' });
 * console.log(data); // { name: 'test' }
 * ```
 */
export declare function load(
  yamlStr: string,
  options?: LoadOptions | undefined | null
): unknown;

/**
 * Parse a YAML string containing multiple documents with options (js-yaml compatible).
 *
 * This is the js-yaml compatible `loadAll()` function that accepts an options object.
 * Currently all schemas behave as `SafeSchema` (safe by default).
 *
 * @param yamlStr - A YAML string potentially containing multiple documents
 * @param options - Optional parsing options (schema, filename, etc.)
 * @returns An array of parsed JavaScript objects
 * @throws Error if the YAML is invalid or input exceeds 100MB
 *
 * @example
 * ```javascript
 * const { loadAll, SAFE_SCHEMA } = require('@fast-yaml/core');
 *
 * const docs = loadAll('---\nfoo: 1\n---\nbar: 2', { schema: 'SafeSchema' });
 * console.log(docs); // [{ foo: 1 }, { bar: 2 }]
 * ```
 */
export declare function loadAll(
  yamlStr: string,
  options?: LoadOptions | undefined | null
): Array<unknown>;

// ============================================================================
// Aliases for js-yaml compatibility
// ============================================================================

/** Alias for safeDump (js-yaml compatibility). */
export declare const dump: typeof safeDump;
