/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Represents a position in a YAML source file.
 *
 * Used to indicate where errors occur during parsing.
 *
 * # Example
 *
 * ```javascript
 * const { Mark } = require('@fast-yaml/core');
 *
 * const mark = new Mark('<input>', 5, 10);
 * console.log(mark.name);   // '<input>'
 * console.log(mark.line);   // 5
 * console.log(mark.column); // 10
 * console.log(mark.toString()); // '<input>:5:10'
 * ```
 */
export declare class Mark {
  /** The name of the source (e.g., filename or '<input>'). */
  readonly name: string
  /** The line number (0-indexed). */
  readonly line: number
  /** The column number (0-indexed). */
  readonly column: number
  /**
   * Create a new Mark instance.
   *
   * # Arguments
   *
   * * `name` - The source name (e.g., filename)
   * * `line` - The line number (0-indexed)
   * * `column` - The column number (0-indexed)
   */
  constructor(name: string, line: number, column: number)
  /**
   * Get a string representation of the mark.
   *
   * Returns format: "name:line:column"
   */
  toString(): string
}

/** Options for YAML serialization. */
export interface DumpOptions {
  /** If true, sort object keys alphabetically (default: false) */
  sortKeys?: boolean
  /**
   * Allow unicode characters (default: true).
   * Note: yaml-rust2 always outputs unicode; this is accepted for API compatibility.
   */
  allowUnicode?: boolean
  /**
   * Indentation width in spaces (default: 2).
   * Valid range: 1-9 (values outside this range will be clamped).
   */
  indent?: number
  /**
   * Maximum line width for wrapping (default: 80).
   * Valid range: 20-1000 (values outside this range will be clamped).
   */
  width?: number
  /**
   * Default flow style for collections (default: null).
   * - null: Use block style (multi-line)
   * - true: Force flow style (inline: [...], {...})
   * - false: Force block style (explicit)
   */
  defaultFlowStyle?: boolean
  /** Add explicit document start marker `---` (default: false). */
  explicitStart?: boolean
}

/**
 * Parse a YAML string with options (js-yaml compatible).
 *
 * This is the js-yaml compatible `load()` function that accepts an options object.
 * Currently all schemas behave as `SafeSchema` (safe by default).
 *
 * # Arguments
 *
 * * `yaml_str` - A YAML document as a string
 * * `options` - Optional parsing options (schema, filename, etc.)
 *
 * # Returns
 *
 * The parsed YAML document as JavaScript objects
 *
 * # Errors
 *
 * Throws an error if:
 * - The YAML is invalid
 * - Input exceeds size limit (100MB)
 *
 * # Example
 *
 * ```javascript
 * const { load, SAFE_SCHEMA } = require('@fast-yaml/core');
 *
 * const data = load('name: test', { schema: 'SafeSchema' });
 * console.log(data); // { name: 'test' }
 * ```
 */
export declare function load(yamlStr: string, options?: LoadOptions | undefined | null): NapiResult<unknown>

/**
 * Parse a YAML string containing multiple documents with options (js-yaml compatible).
 *
 * This is the js-yaml compatible `loadAll()` function that accepts an options object.
 * Currently all schemas behave as `SafeSchema` (safe by default).
 *
 * # Arguments
 *
 * * `yaml_str` - A YAML string potentially containing multiple documents
 * * `options` - Optional parsing options (schema, filename, etc.)
 *
 * # Returns
 *
 * An array of parsed JavaScript objects
 *
 * # Errors
 *
 * Throws an error if:
 * - The YAML is invalid
 * - Input exceeds size limit (100MB)
 *
 * # Example
 *
 * ```javascript
 * const { loadAll, SAFE_SCHEMA } = require('@fast-yaml/core');
 *
 * const docs = loadAll('---
foo: 1
---
bar: 2', { schema: 'SafeSchema' });
 * console.log(docs); // [{ foo: 1 }, { bar: 2 }]
 * ```
 */
export declare function loadAll(yamlStr: string, options?: LoadOptions | undefined | null): NapiResult<Array<unknown>>

/** Options for YAML parsing (js-yaml compatible). */
export interface LoadOptions {
  /**
   * YAML schema to use for parsing (default: `SafeSchema`).
   * Currently all schemas behave as `SafeSchema` (safe by default).
   */
  schema?: Schema
  /** Filename or source name for error messages (default: `<input>`). */
  filename?: string
  /**
   * Allow duplicate keys in mappings (default: true).
   * Note: fast-yaml always allows duplicates; this is for API compatibility.
   */
  allowDuplicateKeys?: boolean
}

/**
 * Serialize a JavaScript object to a YAML string.
 *
 * This is equivalent to js-yaml's `safeDump()` and `PyYAML`'s `safe_dump()`.
 *
 * # Arguments
 *
 * * `data` - A JavaScript object to serialize (Object, Array, string, number, boolean, null)
 * * `options` - Optional serialization options
 *
 * # Returns
 *
 * A YAML string representation of the object
 *
 * # Errors
 *
 * Throws an error if the object contains non-serializable types.
 *
 * # Example
 *
 * ```javascript
 * const { safeDump } = require('@fast-yaml/core');
 *
 * const yaml = safeDump({ name: 'test', value: 123 });
 * console.log(yaml); // 'name: test
value: 123
'
 * ```
 */
export declare function safeDump(data: unknown, options?: DumpOptions | undefined | null): NapiResult<string>

/**
 * Serialize multiple JavaScript objects to a YAML string with document separators.
 *
 * This is equivalent to js-yaml's `safeDumpAll()` and `PyYAML`'s `safe_dump_all()`.
 *
 * # Arguments
 *
 * * `documents` - An array of JavaScript objects to serialize
 * * `options` - Optional serialization options
 *
 * # Returns
 *
 * A YAML string with multiple documents separated by "---"
 *
 * # Errors
 *
 * Throws an error if:
 * - Any object cannot be serialized
 * - Total output size exceeds 100MB limit
 *
 * # Security
 *
 * Maximum output size is limited to 100MB to prevent memory exhaustion.
 *
 * # Example
 *
 * ```javascript
 * const { safeDumpAll } = require('@fast-yaml/core');
 *
 * const yaml = safeDumpAll([{ a: 1 }, { b: 2 }]);
 * console.log(yaml); // '---
a: 1
---
b: 2
'
 * ```
 */
export declare function safeDumpAll(documents: Array<unknown>, options?: DumpOptions | undefined | null): NapiResult<string>

/**
 * Parse a YAML string and return a JavaScript object.
 *
 * This is equivalent to js-yaml's `safeLoad()` and `PyYAML`'s `safe_load()`.
 *
 * # Arguments
 *
 * * `yaml_str` - A YAML document as a string
 *
 * # Returns
 *
 * The parsed YAML document as JavaScript objects (Object, Array, string, number, boolean, null)
 *
 * # Errors
 *
 * Throws an error if:
 * - The YAML is invalid
 * - Input exceeds size limit (100MB)
 *
 * # Security
 *
 * Maximum input size is limited to 100MB to prevent denial-of-service attacks.
 *
 * # Example
 *
 * ```javascript
 * const { safeLoad } = require('@fast-yaml/core');
 *
 * const data = safeLoad('name: test
value: 123');
 * console.log(data); // { name: 'test', value: 123 }
 * ```
 */
export declare function safeLoad(yamlStr: string): NapiResult<unknown>

/**
 * Parse a YAML string containing multiple documents.
 *
 * This is equivalent to js-yaml's `safeLoadAll()` and `PyYAML`'s `safe_load_all()`.
 *
 * # Arguments
 *
 * * `yaml_str` - A YAML string potentially containing multiple documents
 *
 * # Returns
 *
 * An array of parsed JavaScript objects
 *
 * # Errors
 *
 * Throws an error if:
 * - The YAML is invalid
 * - Input exceeds size limit (100MB)
 *
 * # Security
 *
 * Maximum input size is limited to 100MB to prevent denial-of-service attacks.
 *
 * # Example
 *
 * ```javascript
 * const { safeLoadAll } = require('@fast-yaml/core');
 *
 * const docs = safeLoadAll('---
foo: 1
---
bar: 2');
 * console.log(docs); // [{ foo: 1 }, { bar: 2 }]
 * ```
 */
export declare function safeLoadAll(yamlStr: string): NapiResult<Array<unknown>>

/**
 * YAML schema types for parsing behavior (js-yaml compatible).
 *
 * All schemas currently behave as `SAFE_SCHEMA` (safe by default).
 * The schema parameter is accepted for API compatibility with js-yaml.
 */
export declare const enum Schema {
  /**
   * Safe schema - only safe data types (default).
   * Equivalent to `PyYAML`'s `SafeLoader`.
   */
  SafeSchema = 'SafeSchema',
  /** JSON schema - strict JSON subset of YAML. */
  JsonSchema = 'JsonSchema',
  /** Core schema - YAML 1.2.2 Core Schema. */
  CoreSchema = 'CoreSchema',
  /** Failsafe schema - minimal safe subset. */
  FailsafeSchema = 'FailsafeSchema'
}

/**
 * Get the library version.
 *
 * Returns the version string of the fast-yaml-nodejs crate.
 *
 * # Examples
 *
 * ```javascript
 * const { version } = require('@fast-yaml/core');
 * console.log(version()); // "0.1.0"
 * ```
 */
export declare function version(): string
